// src/routes/(public)/about/founders/+page.svelte
<svelte:head>
	<title>The Ten Founders — Kappa Alpha Psi®</title>
	<meta name="description" content="The ten founders of Kappa Alpha Psi Fraternity, Inc. who established the organization on January 5, 1911 at Indiana University Bloomington." />
</svelte:head>

<section class="founders-hero">
	<div class="founders-hero-bg" aria-hidden="true"></div>
	<div class="founders-hero-overlay" aria-hidden="true"></div>
	<div class="container" style="position:relative; z-index:2; text-align:center;">
		<h1 style="font-size:clamp(1.8rem, 4vw, 2.8rem); color:var(--white); font-weight:700; letter-spacing:-0.5px; margin-bottom:12px;">The Ten Founders</h1>
		<div class="hero-divider"><span>&#9670;</span></div>
		<p style="font-size:0.95rem; opacity:0.8; max-width:640px; font-weight:400; margin:0 auto; font-family:var(--font-sans); line-height:1.7; color:var(--white);">On January 5, 1911, ten visionary men at Indiana University Bloomington founded Kappa Alpha Psi Fraternity, Inc.</p>
	</div>
</section>

<section class="section">
	<div class="container" style="text-align:center;">
		<p style="max-width:700px; margin:0 auto; font-size:1.05rem; color:var(--gray-600); line-height:1.85;">
			The story of Kappa Alpha Psi begins with ten men who shared a common vision: to create a brotherhood
			built on the fundamental purpose of <strong>achievement</strong>. Meeting in the early months of the
			1910–1911 academic year at Indiana University, these ten founders forged a bond that has endured for
			over a century and inspired more than 150,000 men to carry their legacy forward.
		</p>
	</div>
</section>

<!-- Elder Watson Diggs — Featured -->
<section class="section section--cream">
	<div class="container">
		<div class="founder-feature">
			<div class="founder-feature-photo">
				<img src="/images/founders/diggs.jpg" alt="Elder Watson Diggs" />
			</div>
			<div class="founder-feature-info">
				<div class="section-label">Permanent Chairman</div>
				<div class="rule"></div>
				<h2 style="font-family:var(--font-serif); font-size:clamp(1.8rem, 4vw, 2.5rem); font-weight:700; margin-bottom:8px; color:var(--black);">Elder Watson Diggs</h2>
				<p style="font-size:0.9rem; color:var(--crimson); font-weight:600; font-style:italic; margin-bottom:16px;">"The Dreamer"</p>
				<p style="font-size:1rem; color:var(--gray-600); line-height:1.85; margin-bottom:12px;">
					Born December 23, 1883, in Christian County, Kentucky. The visionary leader who conceived the idea
					of the fraternity. His guiding principle was "ACHIEVEMENT in every field of human endeavor."
				</p>
				<p style="font-size:1rem; color:var(--gray-600); line-height:1.85;">
					Diggs served as Permanent Chairman and devoted his life to building the fraternity's foundation
					and ideals. His vision of a brotherhood dedicated to achievement has inspired generations of
					Kappa men across the globe.
				</p>
			</div>
		</div>
	</div>
</section>

<!-- Remaining Founders -->
<section class="section">
	<div class="container">
		<div style="text-align:center; margin-bottom:48px;">
			<div class="section-label">The Founders</div>
			<div class="rule rule--center"></div>
			<h2 class="section-title">The Men Who Built the Brotherhood</h2>
		</div>

		<div class="founders-grid">
			{#each [
				{ name: 'Byron Kenneth Armstrong', role: 'Sergeant-at-Arms', nickname: '"Boomski"', photo: 'armstrong.jpg', born: 'Born April 8, 1892, Westfield, IN', bio: 'A dedicated organizer who earned a Ph.D. from the University of Michigan and went on to a distinguished career in education and scholarship.' },
				{ name: 'Guy Levis Grant', role: 'Founder', nickname: '', photo: 'grant.jpg', born: 'Born April 9, 1891, New Albany, IN', bio: 'Practiced dentistry for over 50 years in Indianapolis, becoming one of the city\'s most respected dental professionals.' },
				{ name: 'Marcus Peter Blakemore', role: 'Founder', nickname: '"Blakie"', photo: 'blakemore.jpg', born: 'Born January 3, 1889, Franklin, IN', bio: 'A World War I veteran who served his country with honor and helped establish the fraternity\'s early organizational structure.' },
				{ name: 'Ezra Dee Alexander', role: 'Founder', nickname: '"Dee"', photo: 'alexander.jpg', born: 'Born July 18, 1891, Bloomington, IN', bio: 'Practiced medicine for nearly 50 years, serving his community with dedication and compassion throughout his career.' },
				{ name: 'John Milton Lee', role: 'Secretary', nickname: '', photo: 'lee.jpg', born: 'Born September 7, 1890, Danville, IN', bio: 'An idealist and tireless worker, Lee was instrumental in documenting and preserving the fraternity\'s founding principles and early history.' },
				{ name: 'Henry Tourner Asher', role: 'Founder', nickname: '', photo: 'asher.jpg', born: 'Born June 30, 1890, Owensboro, KY', bio: 'The son of a Baptist minister, Asher brought a deep sense of moral purpose and spiritual conviction to the fraternity\'s founding ideals.' },
				{ name: 'Edward Giles Irvin', role: 'Founder', nickname: '', photo: 'irvin.jpg', born: 'Born August 13, 1893, Spencer, IN', bio: 'The youngest founder at just 17 years of age, demonstrating remarkable maturity and vision beyond his years.' },
				{ name: 'George Wesley Edmonds', role: 'Founder', nickname: '', photo: 'edmonds.jpg', born: 'Born August 13, 1890, Vanderburgh County, IN', bio: 'An integral part of the founding group who helped establish the fraternity\'s values and organizational framework.' },
				{ name: 'Paul Waymond Caine', role: 'Founder', nickname: '', photo: 'caine.jpg', born: 'Born May 17, 1890, Greencastle, IN', bio: 'An entrepreneur and chef who embodied the fraternity\'s spirit of achievement in every field of human endeavor.' }
			] as founder}
				<div class="founder-card">
					<div class="founder-photo">
						<img src="/images/founders/{founder.photo}" alt={founder.name} />
					</div>
					<h3 class="founder-name">{founder.name}</h3>
					<p class="founder-role">{founder.role}</p>
					{#if founder.nickname}
						<p class="founder-nickname">{founder.nickname}</p>
					{/if}
					<p class="founder-born">{founder.born}</p>
					<p class="founder-bio">{founder.bio}</p>
				</div>
			{/each}
		</div>
	</div>
</section>

<!-- Legacy -->
<section class="section section--cream">
	<div class="container" style="text-align:center; max-width:700px;">
		<div class="section-label" style="color:var(--gold);">January 5, 1911</div>
		<div class="rule rule--center" style="background:var(--gold);"></div>
		<h2 class="section-title">Achievement in Every Field of Human Endeavor</h2>
		<p style="font-size:1.025rem; color:var(--gray-600); line-height:1.85; margin-top:16px;">
			The legacy of these ten founders lives on in every chapter, every program, and every brother
			of Kappa Alpha Psi Fraternity, Inc. Their vision of a brotherhood dedicated to achievement
			continues to inspire and transform lives across the globe.
		</p>
		<a href="/about/history" class="btn btn--primary" style="margin-top:24px;">Read Our Full History</a>
	</div>
</section>

<style>
	/* Founders Hero with blended group photo */
	.founders-hero {
		position: relative; overflow: hidden;
		padding: clamp(80px, 12vw, 160px) 0;
	}
	.founders-hero-bg {
		position: absolute; inset: 0; z-index: 0;
		background: url('/images/Founders.webp') center center / contain no-repeat;
		background-color: #3D0000;
		opacity: 0.2;
	}
	.founders-hero-overlay {
		position: absolute; inset: 0; z-index: 1;
		background: linear-gradient(150deg, rgba(61,0,0,0.92) 0%, rgba(92,0,0,0.85) 50%, rgba(61,0,0,0.92) 100%);
	}
	.founders-hero::after {
		content: ''; position: absolute; bottom: -1px; left: 0; right: 0;
		height: 60px; background: var(--white);
		clip-path: ellipse(60% 100% at 50% 100%);
		z-index: 3;
	}

	/* Featured Founder (Diggs) */
	.founder-feature {
		display: grid; grid-template-columns: 260px 1fr; gap: 56px; align-items: center;
	}
	.founder-feature-photo {
		width: 260px; height: 260px; margin: 0 auto;
		border-radius: 50%; overflow: hidden;
		border: 5px solid var(--white);
		box-shadow: 0 12px 40px rgba(0,0,0,0.12);
		transition: transform 0.4s ease, box-shadow 0.4s ease, border-color 0.3s ease;
	}
	.founder-feature-photo:hover {
		transform: translateY(-6px);
		box-shadow: 0 16px 50px rgba(139,0,0,0.2);
		border-color: var(--gold);
	}
	.founder-feature-photo img { width: 100%; height: 100%; object-fit: cover; object-position: center center; }

	/* Founder Grid */
	.founders-grid {
		display: flex; flex-wrap: wrap; justify-content: center; gap: 40px;
	}
	.founder-card {
		text-align: center; width: 220px;
		display: flex; flex-direction: column; align-items: center;
		transition: transform 0.3s ease;
	}
	.founder-card:hover { transform: translateY(-4px); }
	.founder-photo {
		width: 180px; height: 180px; margin: 0 auto 18px;
		border-radius: 50%; overflow: hidden;
		border: 4px solid var(--white);
		box-shadow: 0 8px 28px rgba(0,0,0,0.1);
		transition: box-shadow 0.3s ease, border-color 0.3s ease;
	}
	.founder-card:hover .founder-photo {
		box-shadow: 0 12px 40px rgba(139,0,0,0.18);
		border-color: var(--gold);
	}
	.founder-photo img { width: 100%; height: 100%; object-fit: cover; object-position: center center; }
	.founder-name {
		font-family: var(--font-serif); font-size: 1.1rem; font-weight: 700;
		color: var(--black); margin-bottom: 4px;
	}
	.founder-role {
		font-size: 0.75rem; color: var(--crimson); font-weight: 600;
		text-transform: uppercase; letter-spacing: 0.5px;
		position: relative; display: inline-block; padding-bottom: 8px;
	}
	.founder-role::after {
		content: ''; position: absolute; bottom: 0; left: 50%; transform: translateX(-50%);
		width: 32px; height: 2px; background: var(--gold); border-radius: 1px;
	}
	.founder-nickname {
		font-size: 0.85rem; color: var(--gold); font-style: italic;
		font-family: var(--font-serif); margin-top: 4px;
	}
	.founder-born {
		font-size: 0.78rem; color: var(--gray-400); margin-top: 8px;
	}
	.founder-bio {
		font-size: 0.85rem; color: var(--gray-600); line-height: 1.7;
		margin-top: 8px; text-align: center;
		max-height: 0; overflow: hidden; opacity: 0;
		transition: max-height 0.4s ease, opacity 0.3s ease;
	}
	.founder-card:hover .founder-bio {
		max-height: 200px; opacity: 1;
	}

	@media (max-width: 768px) {
		.founder-feature { grid-template-columns: 1fr; gap: 32px; }
		.founder-feature-photo { width: 200px; height: 200px; }
		.founders-grid { gap: 24px; }
		.founder-card { width: 200px; }
		.founder-photo { width: 140px; height: 140px; }
		.founder-bio { max-height: none; opacity: 1; }
	}
</style>

// src/app/founders/page.tsx
import type { Metadata } from 'next';
import PublicLayout from '@/components/PublicLayout';

export const metadata: Metadata = {
  title: 'Founders — Kappa Alpha Psi® Fraternity, Inc.',
  description:
    'The ten founders of Kappa Alpha Psi® Fraternity, Inc. — ten men who on January 5, 1911, created a legacy spanning more than a century.',
};

const founders = [
  {
    number: 1,
    name: 'Elder Watson Diggs',
    born: 'December 23, 1883',
    nickname: 'The Dreamer',
    description: "The primary visionary of the fraternity's founding. A graduate of Howard University, Diggs conceived the idea of a fraternity dedicated to Achievement in every field of human endeavor. His unwavering vision and charismatic leadership unified the other nine founders and drove the organization from concept to reality.",
    role: 'Chief Founder & Visionary',
  },
  {
    number: 2,
    name: 'Byron Kenneth Armstrong',
    born: 'April 8, 1892',
    nickname: 'Boomski',
    description: "One of the most intellectually versatile founders, Armstrong's academic interests encompassed philosophy, mathematics, and sociology. His broad intellectual foundation helped shape the fraternity's commitment to scholarship across all fields of human endeavor.",
    role: 'Scholar & Philosopher',
  },
  {
    number: 3,
    name: 'Guy Levis Grant',
    born: 'April 9, 1891',
    nickname: null,
    description: "Grant earned his Doctor of Dental Surgery (D.D.S.) degree from Indiana Dental School and went on to practice dentistry for more than 50 years. His long career in a professional field embodied the fraternity's achievement-focused mission.",
    role: 'Dentist & Professional',
  },
  {
    number: 4,
    name: 'Marcus Peter Blakemore',
    born: 'January 3, 1889',
    nickname: 'Blakie',
    description: "Known among his brothers as 'Blakie,' Blakemore demonstrated the highest form of patriotism and service when he answered the call to serve his country during World War I. His military service reflected the character of selfless dedication that the fraternity would foster for generations.",
    role: 'Military Veteran & Patriot',
  },
  {
    number: 5,
    name: 'Ezra Dee Alexander',
    born: 'July 18, 1891',
    nickname: 'Dee',
    description: "Known as 'Dee,' Alexander earned his M.D. from Indiana University Medical School, becoming a physician dedicated to the health of his community. His medical career exemplified the fraternity's principle that achievement must be coupled with service to others.",
    role: 'Physician & Healer',
  },
  {
    number: 6,
    name: 'John Milton Lee',
    born: 'September 7, 1890',
    nickname: null,
    description: "Described by fellow founders as a loyal and tireless worker, Lee contributed the organizational persistence and dedication that transformed an inspired vision into a functional fraternity. His consistent effort in the early organizational work was indispensable to the fraternity's establishment.",
    role: 'Organizational Leader',
  },
  {
    number: 7,
    name: 'Henry Tourner Asher',
    born: 'June 30, 1890',
    nickname: null,
    description: "Asher distinguished himself academically by earning both a Master of Arts degree and a Bachelor of Laws (LL.B.), making him one of the most academically credentialed of the founders. His legal and scholarly training brought rigor and structure to the fraternity's founding documents and principles.",
    role: 'Scholar & Attorney',
  },
  {
    number: 8,
    name: 'Edward Giles Irvin',
    born: 'August 13, 1893',
    nickname: null,
    description: "The youngest of the ten founders at just 17 years of age when the fraternity was chartered, Irvin's youth did not diminish his commitment to the founding ideals. His participation demonstrated that the vision of achievement and brotherhood was not bounded by age.",
    role: 'Youngest Founder',
  },
  {
    number: 9,
    name: 'George Wesley Edmonds',
    born: 'August 13, 1890',
    nickname: null,
    description: "Edmonds served as Corresponding Secretary in the fraternity's earliest days, handling the vital communications that allowed the young organization to grow, connect with potential members, and establish its presence. His administrative skills were the connective tissue of the early fraternity.",
    role: 'Corresponding Secretary',
  },
  {
    number: 10,
    name: 'Paul Waymond Caine',
    born: 'May 17, 1890',
    nickname: null,
    description: "Described as a 'consummate entrepreneur and chef,' Caine brought a spirit of enterprise and creativity to the founding group. His entrepreneurial instincts reflected the fraternity's belief that achievement comes in every form — from the boardroom to the kitchen.",
    role: 'Entrepreneur & Chef',
  },
];

export default function FoundersPage() {
  return (
    <PublicLayout>
      <div className="page-hero">
        <div className="container">
          <h1>The Founders</h1>
          <p>Ten men. One vision. A legacy that spans more than a century.</p>
        </div>
      </div>

      {/* Introduction */}
      <section className="section section--cream">
        <div className="container">
          <div style={{ maxWidth: 900, margin: '0 auto', textAlign: 'center' }}>
            <img
              src="/images/founders.webp"
              alt="The Ten Founders of Kappa Alpha Psi Fraternity"
              className="founders-hero-img"
            />
            <p style={{ fontSize: '1.15rem', marginTop: '2rem' }}>
              On January 5, 1911, ten Black students at Indiana University Bloomington &mdash; barred from campus social life by the racial discrimination of their era &mdash; chose to build rather than accept exclusion. These ten men founded Kappa Alpha Nu, which would become Kappa Alpha Psi&reg; Fraternity, Inc. Their names are revered within the fraternity as the Ten Pearls.
            </p>
          </div>
        </div>
      </section>

      {/* Founders Grid */}
      <section className="section">
        <div className="container">
          <h2 className="section-title">The Ten Pearls</h2>
          <div className="grid grid--2">
            {founders.map((founder) => (
              <div key={founder.number} className="person-card">
                <div className="person-card-img-placeholder" aria-hidden="true">
                  <span style={{ fontSize: '2rem', color: 'var(--gold)' }}>{founder.number}</span>
                </div>
                <div className="person-card-body">
                  <div className="person-card-name">{founder.name}</div>
                  <div className="person-card-title">{founder.role}</div>
                  <p style={{ fontSize: '0.85rem', color: 'var(--crimson)', fontWeight: 600, marginBottom: '0.5rem' }}>
                    Born: {founder.born}
                    {founder.nickname && <span> &mdash; &ldquo;{founder.nickname}&rdquo;</span>}
                  </p>
                  <p style={{ fontSize: '0.9rem', color: 'var(--text-light)', lineHeight: 1.6 }}>{founder.description}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Legacy CTA */}
      <section className="section section--crimson">
        <div className="container" style={{ textAlign: 'center' }}>
          <h2 className="section-title" style={{ color: '#FFF8E1' }}>Their Legacy Lives On</h2>
          <p style={{ color: 'rgba(255,248,225,0.85)', maxWidth: 700, margin: '0 auto 2rem' }}>
            The vision of the Ten Pearls has grown from a single chapter at Indiana University to a global brotherhood of more than 250,000 initiated members across 700+ chapters. Their commitment to Achievement in every field of human endeavor remains the fraternity&apos;s guiding star.
          </p>
          <div style={{ display: 'flex', gap: '1rem', justifyContent: 'center', flexWrap: 'wrap' }}>
            <a href="/history" className="btn btn--white">Read the Full History</a>
            <a href="/membership" className="btn btn--outline-white">Membership Information</a>
          </div>
        </div>
      </section>
    </PublicLayout>
  );
}
